[placeholders.language]
type = "string"
prompt = "Language"
default = "typescript"
choices = ["typescript", "javascript"]

[conditional.'language == "typescript"']
ignore = ["frontend/src/App.jsx", "frontend/src/main.jsx"]

[conditional.'language == "javascript"']
ignore = ["frontend/src/App.tsx", "frontend/src/main.tsx", "frontend/src/vite-env.d.ts", "frontend/tsconfig.app.json", "frontend/tsconfig.json"]
